var dataUrl = 'data/countries/';
var zoom = 2;
var minZoom = 2;
var maxZoom = 16;
var fieldSeparator = ',';
var baseUrl = '//maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png';
var baseAttribution = 'Kudos to <a href="http://www.openstreetmap.org/" target="_blank">OpenStreetMap</a> and contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/" target="_blank">CC-BY-SA</a>';
var subdomains = '1234';
var clusterOptions = {showCoverageOnHover: false, maxClusterRadius: 100, chunkedLoading: true};
var labelColumn = "title";
var opacity = 1.0;
