var countries = [
  { value: 'Andorra', data: 'AD' },
  { value: 'United Arab Emirates', data: 'AE' },
  { value: 'Afghanistan', data: 'AF' },
  { value: 'Antigua and Barbuda', data: 'AG' },
  { value: 'Anguilla', data: 'AI' },
  { value: 'Albania', data: 'AL' },
  { value: 'Armenia', data: 'AM' },
  { value: 'Angola', data: 'AO' },
  { value: 'Asia/Pacific Region', data: 'AP' },
  { value: 'Antarctica', data: 'AQ' },
  { value: 'Argentina', data: 'AR' },
  { value: 'American Samoa', data: 'AS' },
  { value: 'Austria', data: 'AT' },
  { value: 'Australia', data: 'AU' },
  { value: 'Aruba', data: 'AW' },
  { value: 'Aland Islands', data: 'AX' },
  { value: 'Azerbaijan', data: 'AZ' },
  { value: 'Bosnia and Herzegovina', data: 'BA' },
  { value: 'Barbados', data: 'BB' },
  { value: 'Bangladesh', data: 'BD' },
  { value: 'Belgium', data: 'BE' },
  { value: 'Burkina Faso', data: 'BF' },
  { value: 'Bulgaria', data: 'BG' },
  { value: 'Bahrain', data: 'BH' },
  { value: 'Burundi', data: 'BI' },
  { value: 'Benin', data: 'BJ' },
  { value: 'Saint Bartelemey', data: 'BL' },
  { value: 'Bermuda', data: 'BM' },
  { value: 'Brunei Darussalam', data: 'BN' },
  { value: 'Bolivia', data: 'BO' },
  { value: 'Bonaire, Saint Eustatius and Saba', data: 'BQ' },
  { value: 'Brazil', data: 'BR' },
  { value: 'Bahamas', data: 'BS' },
  { value: 'Bhutan', data: 'BT' },
  { value: 'Bouvet Island', data: 'BV' },
  { value: 'Botswana', data: 'BW' },
  { value: 'Belarus', data: 'BY' },
  { value: 'Belize', data: 'BZ' },
  { value: 'Canada', data: 'CA' },
  { value: 'Cocos (Keeling) Islands', data: 'CC' },
  { value: 'Congo, The Democratic Republic of the', data: 'CD' },
  { value: 'Central African Republic', data: 'CF' },
  { value: 'Congo', data: 'CG' },
  { value: 'Switzerland', data: 'CH' },
  { value: 'Cote d\'Ivoire', data: 'CI' },
  { value: 'Cook Islands', data: 'CK' },
  { value: 'Chile', data: 'CL' },
  { value: 'Cameroon', data: 'CM' },
  { value: 'China', data: 'CN' },
  { value: 'Colombia', data: 'CO' },
  { value: 'Costa Rica', data: 'CR' },
  { value: 'Cuba', data: 'CU' },
  { value: 'Cape Verde', data: 'CV' },
  { value: 'Curacao', data: 'CW' },
  { value: 'Christmas Island', data: 'CX' },
  { value: 'Cyprus', data: 'CY' },
  { value: 'Czech Republic', data: 'CZ' },
  { value: 'Germany', data: 'DE' },
  { value: 'Djibouti', data: 'DJ' },
  { value: 'Denmark', data: 'DK' },
  { value: 'Dominica', data: 'DM' },
  { value: 'Dominican Republic', data: 'DO' },
  { value: 'Algeria', data: 'DZ' },
  { value: 'Ecuador', data: 'EC' },
  { value: 'Estonia', data: 'EE' },
  { value: 'Egypt', data: 'EG' },
  { value: 'Western Sahara', data: 'EH' },
  { value: 'Eritrea', data: 'ER' },
  { value: 'Spain', data: 'ES' },
  { value: 'Ethiopia', data: 'ET' },
  { value: 'Europe', data: 'EU' },
  { value: 'Finland', data: 'FI' },
  { value: 'Fiji', data: 'FJ' },
  { value: 'Falkland Islands (Malvinas)', data: 'FK' },
  { value: 'Micronesia, Federated States of', data: 'FM' },
  { value: 'Faroe Islands', data: 'FO' },
  { value: 'France', data: 'FR' },
  { value: 'Gabon', data: 'GA' },
  { value: 'United Kingdom', data: 'GB' },
  { value: 'Grenada', data: 'GD' },
  { value: 'Georgia', data: 'GE' },
  { value: 'French Guiana', data: 'GF' },
  { value: 'Guernsey', data: 'GG' },
  { value: 'Ghana', data: 'GH' },
  { value: 'Gibraltar', data: 'GI' },
  { value: 'Greenland', data: 'GL' },
  { value: 'Gambia', data: 'GM' },
  { value: 'Guinea', data: 'GN' },
  { value: 'Guadeloupe', data: 'GP' },
  { value: 'Equatorial Guinea', data: 'GQ' },
  { value: 'Greece', data: 'GR' },
  { value: 'South Georgia and the South Sandwich Islands', data: 'GS' },
  { value: 'Guatemala', data: 'GT' },
  { value: 'Guam', data: 'GU' },
  { value: 'Guinea-Bissau', data: 'GW' },
  { value: 'Guyana', data: 'GY' },
  { value: 'Hong Kong', data: 'HK' },
  { value: 'Heard Island and McDonald Islands', data: 'HM' },
  { value: 'Honduras', data: 'HN' },
  { value: 'Croatia', data: 'HR' },
  { value: 'Haiti', data: 'HT' },
  { value: 'Hungary', data: 'HU' },
  { value: 'Indonesia', data: 'ID' },
  { value: 'Ireland', data: 'IE' },
  { value: 'Israel', data: 'IL' },
  { value: 'Isle of Man', data: 'IM' },
  { value: 'India', data: 'IN' },
  { value: 'British Indian Ocean Territory', data: 'IO' },
  { value: 'Iraq', data: 'IQ' },
  { value: 'Iran, Islamic Republic of', data: 'IR' },
  { value: 'Iceland', data: 'IS' },
  { value: 'Italy', data: 'IT' },
  { value: 'Jersey', data: 'JE' },
  { value: 'Jamaica', data: 'JM' },
  { value: 'Jordan', data: 'JO' },
  { value: 'Japan', data: 'JP' },
  { value: 'Kenya', data: 'KE' },
  { value: 'Kyrgyzstan', data: 'KG' },
  { value: 'Cambodia', data: 'KH' },
  { value: 'Kiribati', data: 'KI' },
  { value: 'Comoros', data: 'KM' },
  { value: 'Saint Kitts and Nevis', data: 'KN' },
  { value: 'Korea, Democratic People\'s Republic of', data: 'KP' },
  { value: 'Korea, Republic of', data: 'KR' },
  { value: 'Kuwait', data: 'KW' },
  { value: 'Cayman Islands', data: 'KY' },
  { value: 'Kazakhstan', data: 'KZ' },
  { value: 'Lao People\'s Democratic Republic', data: 'LA' },
  { value: 'Lebanon', data: 'LB' },
  { value: 'Saint Lucia', data: 'LC' },
  { value: 'Liechtenstein', data: 'LI' },
  { value: 'Sri Lanka', data: 'LK' },
  { value: 'Liberia', data: 'LR' },
  { value: 'Lesotho', data: 'LS' },
  { value: 'Lithuania', data: 'LT' },
  { value: 'Luxembourg', data: 'LU' },
  { value: 'Latvia', data: 'LV' },
  { value: 'Libyan Arab Jamahiriya', data: 'LY' },
  { value: 'Morocco', data: 'MA' },
  { value: 'Monaco', data: 'MC' },
  { value: 'Moldova, Republic of', data: 'MD' },
  { value: 'Montenegro', data: 'ME' },
  { value: 'Saint Martin', data: 'MF' },
  { value: 'Madagascar', data: 'MG' },
  { value: 'Marshall Islands', data: 'MH' },
  { value: 'Macedonia', data: 'MK' },
  { value: 'Mali', data: 'ML' },
  { value: 'Myanmar', data: 'MM' },
  { value: 'Mongolia', data: 'MN' },
  { value: 'Macao', data: 'MO' },
  { value: 'Northern Mariana Islands', data: 'MP' },
  { value: 'Martinique', data: 'MQ' },
  { value: 'Mauritania', data: 'MR' },
  { value: 'Montserrat', data: 'MS' },
  { value: 'Malta', data: 'MT' },
  { value: 'Mauritius', data: 'MU' },
  { value: 'Maldives', data: 'MV' },
  { value: 'Malawi', data: 'MW' },
  { value: 'Mexico', data: 'MX' },
  { value: 'Malaysia', data: 'MY' },
  { value: 'Mozambique', data: 'MZ' },
  { value: 'Namibia', data: 'NA' },
  { value: 'New Caledonia', data: 'NC' },
  { value: 'Niger', data: 'NE' },
  { value: 'Norfolk Island', data: 'NF' },
  { value: 'Nigeria', data: 'NG' },
  { value: 'Nicaragua', data: 'NI' },
  { value: 'Netherlands', data: 'NL' },
  { value: 'Norway', data: 'NO' },
  { value: 'Nepal', data: 'NP' },
  { value: 'Nauru', data: 'NR' },
  { value: 'Niue', data: 'NU' },
  { value: 'New Zealand', data: 'NZ' },
  { value: 'Oman', data: 'OM' },
  { value: 'Panama', data: 'PA' },
  { value: 'Peru', data: 'PE' },
  { value: 'French Polynesia', data: 'PF' },
  { value: 'Papua New Guinea', data: 'PG' },
  { value: 'Philippines', data: 'PH' },
  { value: 'Pakistan', data: 'PK' },
  { value: 'Poland', data: 'PL' },
  { value: 'Saint Pierre and Miquelon', data: 'PM' },
  { value: 'Pitcairn', data: 'PN' },
  { value: 'Puerto Rico', data: 'PR' },
  { value: 'Palestinian Territory', data: 'PS' },
  { value: 'Portugal', data: 'PT' },
  { value: 'Palau', data: 'PW' },
  { value: 'Paraguay', data: 'PY' },
  { value: 'Qatar', data: 'QA' },
  { value: 'Reunion', data: 'RE' },
  { value: 'Romania', data: 'RO' },
  { value: 'Serbia', data: 'RS' },
  { value: 'Russian Federation', data: 'RU' },
  { value: 'Rwanda', data: 'RW' },
  { value: 'Saudi Arabia', data: 'SA' },
  { value: 'Solomon Islands', data: 'SB' },
  { value: 'Seychelles', data: 'SC' },
  { value: 'Sudan', data: 'SD' },
  { value: 'Sweden', data: 'SE' },
  { value: 'Singapore', data: 'SG' },
  { value: 'Saint Helena', data: 'SH' },
  { value: 'Slovenia', data: 'SI' },
  { value: 'Svalbard and Jan Mayen', data: 'SJ' },
  { value: 'Slovakia', data: 'SK' },
  { value: 'Sierra Leone', data: 'SL' },
  { value: 'San Marino', data: 'SM' },
  { value: 'Senegal', data: 'SN' },
  { value: 'Somalia', data: 'SO' },
  { value: 'Suriname', data: 'SR' },
  { value: 'South Sudan', data: 'SS' },
  { value: 'Sao Tome and Principe', data: 'ST' },
  { value: 'El Salvador', data: 'SV' },
  { value: 'Sint Maarten', data: 'SX' },
  { value: 'Syrian Arab Republic', data: 'SY' },
  { value: 'Swaziland', data: 'SZ' },
  { value: 'Turks and Caicos Islands', data: 'TC' },
  { value: 'Chad', data: 'TD' },
  { value: 'French Southern Territories', data: 'TF' },
  { value: 'Togo', data: 'TG' },
  { value: 'Thailand', data: 'TH' },
  { value: 'Tajikistan', data: 'TJ' },
  { value: 'Tokelau', data: 'TK' },
  { value: 'Timor-Leste', data: 'TL' },
  { value: 'Turkmenistan', data: 'TM' },
  { value: 'Tunisia', data: 'TN' },
  { value: 'Tonga', data: 'TO' },
  { value: 'Turkey', data: 'TR' },
  { value: 'Trinidad and Tobago', data: 'TT' },
  { value: 'Tuvalu', data: 'TV' },
  { value: 'Taiwan', data: 'TW' },
  { value: 'Tanzania, United Republic of', data: 'TZ' },
  { value: 'Ukraine', data: 'UA' },
  { value: 'Uganda', data: 'UG' },
  { value: 'United States Minor Outlying Islands', data: 'UM' },
  { value: 'United States', data: 'US' },
  { value: 'Uruguay', data: 'UY' },
  { value: 'Uzbekistan', data: 'UZ' },
  { value: 'Holy See (Vatican City State)', data: 'VA' },
  { value: 'Saint Vincent and the Grenadines', data: 'VC' },
  { value: 'Venezuela', data: 'VE' },
  { value: 'Virgin Islands, British', data: 'VG' },
  { value: 'Virgin Islands, U.S.', data: 'VI' },
  { value: 'Vietnam', data: 'VN' },
  { value: 'Vanuatu', data: 'VU' },
  { value: 'Wallis and Futuna', data: 'WF' },
  { value: 'Samoa', data: 'WS' },
  { value: 'Yemen', data: 'YE' },
  { value: 'Mayotte', data: 'YT' },
  { value: 'South Africa', data: 'ZA' },
  { value: 'Zambia', data: 'ZM' },
  { value: 'Zimbabwe', data: 'ZW' }
  ];

$('#autocountries').autocomplete({
    lookup: countries,
    open: function () {
        $(this).autocomplete('widget').css('z-index', 99999);
    },
    onSelect: function (suggestion) {
        load_data(suggestion.data);
        bootbox.hideAll();
    }
});
